package com.simats.codeingo.domain

import android.content.Context
import android.content.SharedPreferences
import com.simats.codeingo.data.model.Language
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale

// ══════════════════════════════════════════════════════════════════
// 🌐 LocalizationManager — Language & User Session Profile State
// Exact parity with iOS LocalizationManager.swift (24 languages, 140+ keys)
// ══════════════════════════════════════════════════════════════════
class LocalizationManager private constructor() {

    companion object {
        val instance: LocalizationManager by lazy { LocalizationManager() }
        val shared: LocalizationManager get() = instance
        private const val PREFS_NAME = "duolingo_localization_prefs"
        private const val LAST_OPEN_DATE_KEY = "duolingo_last_open_date_key"
        private const val DAY_STREAK_COUNT_KEY = "duolingo_day_streak_count_key"
        private const val SELECTED_LANG_KEY = "duolingo_selected_language_key"
    }

    private var prefs: SharedPreferences? = null

    private val _selectedLanguage = MutableStateFlow<Language?>(null)
    val selectedLanguage: StateFlow<Language?> = _selectedLanguage.asStateFlow()

    private val _selectedLanguageCode = MutableStateFlow("en")
    val selectedLanguageCode: StateFlow<String> = _selectedLanguageCode.asStateFlow()

    private val _isLoggedIn = MutableStateFlow(true)
    val isLoggedIn: StateFlow<Boolean> = _isLoggedIn.asStateFlow()

    private val _userName = MutableStateFlow("Lokesh Kumar")
    val userName: StateFlow<String> = _userName.asStateFlow()

    private val _userHandle = MutableStateFlow("lokesh_dev")
    val userHandle: StateFlow<String> = _userHandle.asStateFlow()

    private val _dayStreak = MutableStateFlow(1)
    val dayStreak: StateFlow<Int> = _dayStreak.asStateFlow()

    val currentLanguageCode: String
        get() = _selectedLanguageCode.value

    fun initialize(context: Context) {
        val appContext = context.applicationContext
        prefs = appContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

        val savedLangCode = prefs?.getString(SELECTED_LANG_KEY, null)
        if (savedLangCode != null) {
            selectLanguage(savedLangCode)
        }

        checkAndUpdateStreak()
    }

    fun setSelectedLanguage(language: Language?) {
        _selectedLanguage.value = language
        if (language != null) {
            _selectedLanguageCode.value = language.code
            prefs?.edit()?.putString(SELECTED_LANG_KEY, language.code)?.apply()
        }
    }

    fun selectLanguage(code: String) {
        _selectedLanguageCode.value = code
        val match = Language.defaultLanguages.find { it.code == code }
        _selectedLanguage.value = match
        prefs?.edit()?.putString(SELECTED_LANG_KEY, code)?.apply()
    }

    fun updateUserProfile(name: String, handle: String) {
        if (name.isNotEmpty()) _userName.value = name
        if (handle.isNotEmpty()) _userHandle.value = handle
    }

    fun setLoggedIn(loggedIn: Boolean, name: String = "", handle: String = "") {
        _isLoggedIn.value = loggedIn
        if (name.isNotEmpty()) _userName.value = name
        if (handle.isNotEmpty()) _userHandle.value = handle
    }

    fun resetProfileData() {
        _isLoggedIn.value = false
        _userName.value = ""
        _userHandle.value = ""
    }

    fun checkAndUpdateStreak() {
        val calendar = Calendar.getInstance()
        val today = calendar.apply {
            set(Calendar.HOUR_OF_DAY, 0)
            set(Calendar.MINUTE, 0)
            set(Calendar.SECOND, 0)
            set(Calendar.MILLISECOND, 0)
        }.time

        val formatter = SimpleDateFormat("yyyy-MM-dd", Locale.US)
        val todayStr = formatter.format(today)

        val savedDateStr = prefs?.getString(LAST_OPEN_DATE_KEY, null)
        val savedStreak = prefs?.getInt(DAY_STREAK_COUNT_KEY, 1) ?: 1

        if (savedDateStr != null) {
            try {
                val savedDate = formatter.parse(savedDateStr)
                if (savedDate != null) {
                    val savedCal = Calendar.getInstance().apply { time = savedDate }
                    val nowCal = Calendar.getInstance().apply { time = today }
                    val diffMillis = nowCal.timeInMillis - savedCal.timeInMillis
                    val daysDiff = (diffMillis / (1000 * 60 * 60 * 24)).toInt()

                    if (daysDiff == 0) {
                        // Same day
                        _dayStreak.value = maxOf(savedStreak, 1)
                    } else if (daysDiff == 1) {
                        // Consecutive day
                        val newStreak = (if (savedStreak > 0) savedStreak else 1) + 1
                        _dayStreak.value = newStreak
                        prefs?.edit()
                            ?.putString(LAST_OPEN_DATE_KEY, todayStr)
                            ?.putInt(DAY_STREAK_COUNT_KEY, newStreak)
                            ?.apply()
                    } else {
                        // Missed days -> Reset
                        _dayStreak.value = 1
                        prefs?.edit()
                            ?.putString(LAST_OPEN_DATE_KEY, todayStr)
                            ?.putInt(DAY_STREAK_COUNT_KEY, 1)
                            ?.apply()
                    }
                } else {
                    _dayStreak.value = 1
                }
            } catch (e: Exception) {
                _dayStreak.value = 1
            }
        } else {
            // First time opening app: start at 1
            _dayStreak.value = 1
            prefs?.edit()
                ?.putString(LAST_OPEN_DATE_KEY, todayStr)
                ?.putInt(DAY_STREAK_COUNT_KEY, 1)
                ?.apply()
        }
    }

    fun simulateNextDayOpening() {
        val newStreak = _dayStreak.value + 1
        _dayStreak.value = newStreak
        val formatter = SimpleDateFormat("yyyy-MM-dd", Locale.US)
        val todayStr = formatter.format(Date())
        prefs?.edit()
            ?.putString(LAST_OPEN_DATE_KEY, todayStr)
            ?.putInt(DAY_STREAK_COUNT_KEY, newStreak)
            ?.apply()
    }

    fun simulateMissedDaysReset() {
        _dayStreak.value = 0
        prefs?.edit()
            ?.remove(LAST_OPEN_DATE_KEY)
            ?.putInt(DAY_STREAK_COUNT_KEY, 0)
            ?.apply()
    }

    // Dynamic localization translation lookup dictionary matching iOS exactly
    private val translations: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "site_language" to "SITE LANGUAGE:",
            "choose_language" to "CHOOSE LANGUAGE",
            "what_language_do_you_speak" to "What language do you speak?",
            "choose_interface_lang" to "Choose your site and interface language",
            "login_caps" to "LOGIN",
            "signup_caps" to "SIGN UP",
            "get_started_caps" to "GET STARTED",
            "already_have_account_caps" to "I ALREADY HAVE AN ACCOUNT",
            "duolingo_on_the_go" to "Duolingo on the go",
            "hero_subtitle" to "The free, fun, and effective way to learn a language!",
            "why_learn" to "Why learn with Duolingo?",
            "effective_fun" to "Effective & Fun",
            "effective_subtitle" to "Gamified lessons keep you motivated.",
            "personalized" to "Personalized",
            "personalized_subtitle" to "AI tailored to your learning pace.",
            "login_title" to "Log in",
            "create_profile" to "Create profile",
            "email_or_username" to "Email or username",
            "password" to "Password",
            "forgot" to "FORGOT?",
            "name_optional" to "Name (optional)",
            "age" to "Age",
            "create_account" to "CREATE ACCOUNT",
            "terms_privacy" to "By signing in to Duolingo, you agree to our Terms and Privacy Policy.",
            "recaptcha" to "This site is protected by reCAPTCHA Enterprise and the Google Privacy Policy and Terms of Service apply.",
            "site_language_modal" to "Site Language",
            "done" to "Done",
            "google_auth" to "GOOGLE",
            "facebook_auth" to "FACEBOOK",
            "use_another_account" to "USE ANOTHER ACCOUNT",
            "signed_in_google" to "Signed in with Google as %s",
            "welcome_back" to "Welcome back! Logging in...",
            "account_created" to "Account created successfully!",
            "enter_email" to "Please enter your email or username",
            "password_short" to "Password must be at least 4 characters",
            "loading" to "LOADING...",
            "how_much_know" to "How much %s do you know?",
            "new_to_lang" to "I'm new to %s",
            "know_common_words" to "I know some common words",
            "basic_conversations" to "I can have basic conversations",
            "various_topics" to "I can talk about various topics",
            "topics_in_detail" to "I can discuss most topics in detail",
            "continue_caps" to "CONTINUE",
            "section_1_unit_1" to "SECTION 1, UNIT 1",
            "section_1_unit_2" to "SECTION 1, UNIT 2",
            "section_1_unit_3" to "SECTION 1, UNIT 3",
            "section_1_unit_4" to "SECTION 1, UNIT 4",
            "section_1_unit_5" to "SECTION 1, UNIT 5",
            "solo_trip_title" to "Solo trip: Compare travel experiences",
            "compare_travel_experiences" to "Compare travel experiences",
            "ask_about_transportation" to "Solo trip: Debug runtime errors",
            "reserve_hotel_room" to "Solo trip: Setup environment",
            "order_food_drinks" to "Compile code",
            "discuss_travel_plans" to "Deploy application",
            "jump_here" to "JUMP HERE?",
            "start_plus_10_xp" to "RUN +10 XP",
            "loading_next_lesson" to "Loading next module...",
            "getting_things_ready" to "Compiling your environment...",
            "form_basic_sentences" to "Write basic syntax",
            "guidebook" to "DOCS",
            "start" to "RUN",
            "learn" to "CODE",
            "letters" to "VIDEOS",
            "leaderboards" to "RANKINGS",
            "quests" to "ISSUES",
            "shop" to "MARKETPLACE",
            "profile" to "DEVELOPER",
            "more" to "CONSOLE",
            "unlock_leaderboards" to "Unlock Rankings!",
            "unlock_leaderboards_sub" to "Complete 3 more modules to start competing",
            "what_are_leaderboards" to "WHAT ARE RANKINGS?",
            "do_lessons_earn_xp" to "Write code. Earn XP. Compete.",
            "earn_xp_compete_sub" to "Earn XP through coding, then compete with developers in a weekly ranking",
            "complete_lessons_to_start" to "Complete %d more modules to start competing",
            "start_a_lesson" to "START CODING",
            "bronze_league" to "Junior League",
            "top_20_advance" to "Top 20 advance to the next tier!",
            "daily_quests" to "Daily Issues",
            "welcome_title" to "Welcome Developer!",
            "complete_quests_body" to "Resolve issues to earn rewards! Issues refresh every day.",
            "spend_15_mins" to "Spend 15 minutes coding",
            "complete_2_perfect" to "Write 2 perfect scripts",
            "more_quests_unlock_soon" to "More issues unlock soon",
            "monthly_challenges_title" to "Monthly sprints unlock soon!",
            "monthly_challenges_sub" to "Complete each month's sprint to earn exclusive badges",
            "hours_left_tag" to "%d HOURS",
            "view_all" to "VIEW ALL",
            "earn_10_xp" to "Earn 10 XP",
            "you_earned_500_gems" to "You earned 500 gems! Create a profile to spend them in the store!",
            "super_trial_banner_title" to "Start a 1 week free trial to enjoy exclusive Super benefits",
            "start_my_free_7_days" to "START MY FREE 7 DAYS",
            "hearts" to "Hearts",
            "refill_hearts" to "Refill Hearts",
            "refill_hearts_sub" to "Get full hearts so you can worry less about making mistakes in a lesson",
            "full_caps" to "FULL",
            "unlimited_hearts" to "Unlimited Hearts",
            "unlimited_hearts_sub" to "Never run out of hearts with Super!",
            "free_trial_caps" to "FREE TRIAL",
            "power_ups" to "Power-Ups",
            "streak_freeze" to "Streak Freeze",
            "streak_freeze_sub" to "Streak Freeze allows your streak to remain in place for one full day of inactivity.",
            "equipped_status" to "%d / 2 EQUIPPED",
            "statistics" to "Statistics",
            "day_streak" to "Day streak",
            "total_xp" to "Total XP",
            "current_league" to "Current league",
            "top_3_finishes" to "Top 3 finishes",
            "achievements" to "Achievements",
            "wildfire" to "Wildfire",
            "reach_3_day_streak" to "Reach a 3 day streak",
            "sage" to "Sage",
            "earn_100_xp" to "Earn 100 XP",
            "champion" to "Champion",
            "unlock_leaderboards_10" to "Unlock Leaderboards by completing 10 lessons",
            "add_friends" to "Add friends",
            "find_friends" to "Find friends",
            "invite_friends" to "Invite friends",
            "joined_september" to "Joined September 2026",
            "none_league" to "None",
            "settings_caps" to "SETTINGS",
            "logout_caps" to "LOG OUT",
            "logged_out_success" to "Logged out successfully",
            "sound_effects" to "Sound Effects",
            "haptic_feedback" to "Haptic Feedback",
            "daily_goal" to "Daily Goal",
            "account" to "ACCOUNT",
            "create_profile_title" to "Create a profile to save your progress!",
            "talk_about_food" to "Talk about food",
            "lets_go" to "LET'S GO!",
            "how_old_are_you" to "How old are you?",
            "providing_age_info" to "Providing your age ensures you get the right Duolingo experience. For more details, please visit our Privacy Policy.",
            "next_caps" to "NEXT",
            "create_your_profile" to "Create your profile",
            "lets_learn_lang" to "Let's learn %s!",
            "get_to_know_characters" to "Get to know the characters and sounds for %s",
            "learn_the_letters" to "LEARN THE LETTERS",
            "borrowed_characters" to "Borrowed Characters",
            "vowels" to "Vowels",
            "combinations" to "Combinations",
            "practice_sound" to "Practice Sound",
            "tap_to_listen" to "Tap a character card to listen to its pronunciation"
        ),
        "es" to mapOf(
            "site_language" to "IDIOMA DEL SITIO:",
            "choose_language" to "ELEGIR IDIOMA",
            "what_language_do_you_speak" to "¿Qué idioma hablas?",
            "choose_interface_lang" to "Elige el idioma del sitio e interfaz",
            "login_caps" to "INICIAR SESIÓN",
            "signup_caps" to "REGISTRARSE",
            "get_started_caps" to "EMPEZAR",
            "already_have_account_caps" to "YA TENGO UNA CUENTA",
            "duolingo_on_the_go" to "Duolingo sobre la marcha",
            "hero_subtitle" to "¡La forma gratuita, divertida y eficaz de aprender un idioma!",
            "why_learn" to "¿Por qué aprender con Duolingo?",
            "effective_fun" to "Efectivo y divertido",
            "effective_subtitle" to "Las lecciones gamificadas te mantienen motivado.",
            "personalized" to "Personalizado",
            "personalized_subtitle" to "IA adaptada a tu ritmo de aprendizaje.",
            "login_title" to "Iniciar sesión",
            "create_profile" to "Crear perfil",
            "email_or_username" to "Correo o nombre de usuario",
            "password" to "Contraseña",
            "forgot" to "¿OLVIDASTE?",
            "name_optional" to "Nombre (opcional)",
            "age" to "Edad",
            "create_account" to "CREAR CUENTA",
            "terms_privacy" to "Al iniciar sesión en Duolingo, aceptas nuestros Términos y Política de Privacidad.",
            "recaptcha" to "Este sitio está protegido por reCAPTCHA Enterprise.",
            "site_language_modal" to "Idioma del sitio",
            "done" to "Hecho",
            "welcome_back" to "¡Bienvenido de nuevo! Iniciando sesión...",
            "account_created" to "¡Cuenta creada con éxito!",
            "enter_email" to "Ingresa tu correo o nombre de usuario",
            "password_short" to "La contraseña debe tener al menos 4 caracteres",
            "loading" to "CARGANDO...",
            "how_much_know" to "¿Cuánto %s sabes?",
            "new_to_lang" to "Soy nuevo en %s",
            "know_common_words" to "Sé algunas palabras comunes",
            "basic_conversations" to "Puedo tener conversaciones básicas",
            "various_topics" to "Puedo hablar de varios temas",
            "topics_in_detail" to "Puedo discutir la mayoría de temas en detalle",
            "continue_caps" to "CONTINUAR"
        ),
        "hi" to mapOf(
            "site_language" to "साइट की भाषा:",
            "choose_language" to "भाषा चुनें",
            "what_language_do_you_speak" to "आप कौन सी भाषा बोलते हैं?",
            "choose_interface_lang" to "अपनी भाषा चुनें",
            "login_caps" to "लॉग इन",
            "signup_caps" to "साइन अप",
            "get_started_caps" to "शुरू करें",
            "already_have_account_caps" to "मेरा पहले से ही एक खाता है",
            "duolingo_on_the_go" to "चलते-फिरते डुओलिंगो",
            "hero_subtitle" to "भाषा सीखने का मुफ़्त, मज़ेदार और असरदार तरीका!",
            "why_learn" to "डुओलिंगो से क्यों सीखें?",
            "effective_fun" to "असरदार और मज़ेदार",
            "effective_subtitle" to "गेम जैसे पाठ आपको प्रेरित रखते हैं।",
            "personalized" to "व्यक्तिगत",
            "personalized_subtitle" to "आपकी गति के अनुकूल एआई।",
            "login_title" to "लॉग इन करें",
            "create_profile" to "प्रोफ़ाइल बनाएं",
            "email_or_username" to "ईमेल या यूज़रनेम",
            "password" to "पासवर्ड",
            "forgot" to "भूल गए?",
            "name_optional" to "नाम (वैकल्पिक)",
            "age" to "उम्र",
            "create_account" to "खाता बनाएं",
            "terms_privacy" to "लॉग इन करके, आप हमारी शर्तों और गोपनीयता नीति से सहमत होते हैं।",
            "recaptcha" to "यह साइट reCAPTCHA Enterprise द्वारा सुरक्षित है।",
            "site_language_modal" to "साइट की भाषा",
            "done" to "संपन्न",
            "welcome_back" to "वापसी पर स्वागत है! लॉग इन हो रहा है...",
            "account_created" to "खाता सफलतापूर्वक बन गया!",
            "enter_email" to "कृपया अपना ईमेल या यूज़रनेम दर्ज करें",
            "password_short" to "पासवर्ड कम से कम 4 अक्षरों का होना चाहिए",
            "loading" to "लोड हो रहा है...",
            "how_much_know" to "आप कितनी %s जानते हैं?",
            "new_to_lang" to "मैं %s में नया हूँ",
            "know_common_words" to "मुझे कुछ आम शब्द पता हैं",
            "basic_conversations" to "मैं बुनियादी बातचीत कर सकता हूँ",
            "various_topics" to "मैं विभिन्न विषयों पर बात कर सकता हूँ",
            "topics_in_detail" to "मैं अधिकांश विषयों पर विस्तार से चर्चा कर सकता हूँ",
            "continue_caps" to "आगे बढ़ें"
        ),
        "pt" to mapOf(
            "site_language" to "IDIOMA DO SITE:",
            "choose_language" to "ESCOLHER IDIOMA",
            "what_language_do_you_speak" to "Qual idioma você fala?",
            "choose_interface_lang" to "Escolha o idioma da interface",
            "login_caps" to "ENTRAR",
            "signup_caps" to "CADASTRAR-SE",
            "get_started_caps" to "COMEÇAR",
            "already_have_account_caps" to "JÁ TENHO UMA CONTA",
            "duolingo_on_the_go" to "Duolingo em qualquer lugar",
            "hero_subtitle" to "A maneira gratuita, divertida e eficaz de aprender um idioma!",
            "why_learn" to "Por que aprender com o Duolingo?",
            "effective_fun" to "Eficaz e divertido",
            "effective_subtitle" to "Lições gamificadas mantêm você motivado.",
            "personalized" to "Personalizado",
            "personalized_subtitle" to "IA adaptada ao seu ritmo de aprendizado.",
            "login_title" to "Entrar",
            "create_profile" to "Criar perfil",
            "email_or_username" to "E-mail ou nome de usuário",
            "password" to "Senha",
            "forgot" to "ESQUECEU?",
            "name_optional" to "Nome (opcional)",
            "age" to "Idade",
            "create_account" to "CRIAR CONTA",
            "terms_privacy" to "Ao entrar no Duolingo, você concorda com nossos Termos e Política de Privacidade.",
            "recaptcha" to "Este site é protegido pelo reCAPTCHA Enterprise.",
            "site_language_modal" to "Idioma do site",
            "done" to "Concluído",
            "welcome_back" to "Bem-vindo de volta! Entrando...",
            "account_created" to "Conta criada com sucesso!",
            "enter_email" to "Por favor, digite seu e-mail ou nome de usuário",
            "password_short" to "A senha deve ter pelo menos 4 caracteres",
            "loading" to "CARREGANDO...",
            "how_much_know" to "Quanto de %s você sabe?",
            "new_to_lang" to "Sou novo em %s",
            "know_common_words" to "Sei algumas palavras comuns",
            "basic_conversations" to "Consigo ter conversas básicas",
            "various_topics" to "Consigo falar sobre vários assuntos",
            "topics_in_detail" to "Consigo discutir a maioria dos tópicos em detalhes",
            "continue_caps" to "CONTINUAR"
        ),
        "ru" to mapOf(
            "site_language" to "ЯЗЫК САЙТА:",
            "choose_language" to "ВЫБРАТЬ ЯЗЫК",
            "what_language_do_you_speak" to "На каком языке вы говорите?",
            "choose_interface_lang" to "Выберите язык интерфейса",
            "login_caps" to "ВОЙТИ",
            "signup_caps" to "РЕГИСТРАЦИЯ",
            "get_started_caps" to "НАЧАТЬ",
            "already_have_account_caps" to "У МЕНЯ УЖЕ ЕСТЬ АККАУНТ",
            "duolingo_on_the_go" to "Duolingo всегда с вами",
            "hero_subtitle" to "Бесплатный, весёлый и эффективный способ учить языки!",
            "why_learn" to "Почему именно Duolingo?",
            "effective_fun" to "Эффективно и весело",
            "effective_subtitle" to "Игровые уроки помогают поддерживать мотивацию.",
            "personalized" to "Персонализировано",
            "personalized_subtitle" to "ИИ подстраивается под ваш темп.",
            "login_title" to "Войти",
            "create_profile" to "Создать профиль",
            "email_or_username" to "Эл. почта или имя пользователя",
            "password" to "Пароль",
            "forgot" to "ЗАБЫЛИ?",
            "name_optional" to "Имя (необязательно)",
            "age" to "Возраст",
            "create_account" to "СОЗДАТЬ АККАУНТ",
            "terms_privacy" to "Входя в Duolingo, вы соглашаетесь с Условиями и Политикой конфиденциальности.",
            "recaptcha" to "Сайт защищен reCAPTCHA Enterprise.",
            "site_language_modal" to "Язык сайта",
            "done" to "Готово",
            "welcome_back" to "С возвращением! Вход...",
            "account_created" to "Аккаунт успешно создан!",
            "enter_email" to "Введите почту или имя пользователя",
            "password_short" to "Пароль должен быть не менее 4 символов",
            "loading" to "ЗАГРУЗКА...",
            "how_much_know" to "Сколько %s вы знаете?",
            "new_to_lang" to "Я новичок в %s",
            "know_common_words" to "Я знаю несколько простых слов",
            "basic_conversations" to "Могу вести простые разговоры",
            "various_topics" to "Могу говорить на разные темы",
            "topics_in_detail" to "Могу детально обсуждать большинство тем",
            "continue_caps" to "ПРОДОЛЖИТЬ"
        ),
        "fr" to mapOf(
            "site_language" to "LANGUE DU SITE :",
            "choose_language" to "CHOISIR LA LANGUE",
            "what_language_do_you_speak" to "Quelle langue parlez-vous ?",
            "choose_interface_lang" to "Choisissez la langue de l'interface",
            "login_caps" to "CONNEXION",
            "signup_caps" to "S'INSCRIRE",
            "get_started_caps" to "C'EST PARTI",
            "already_have_account_caps" to "J'AI DÉJÀ UN COMPTE",
            "duolingo_on_the_go" to "Duolingo partout avec vous",
            "hero_subtitle" to "La méthode gratuite, amusante et efficace pour apprendre une langue !",
            "why_learn" to "Pourquoi apprendre avec Duolingo ?",
            "effective_fun" to "Efficace et amusant",
            "effective_subtitle" to "Des leçons ludiques pour rester motivé.",
            "personalized" to "Personnalisé",
            "personalized_subtitle" to "Une IA adaptée à votre rythme d'apprentissage.",
            "login_title" to "Connexion",
            "create_profile" to "Créer un profil",
            "email_or_username" to "E-mail ou nom d'utilisateur",
            "password" to "Mot de passe",
            "forgot" to "OUBLIÉ ?",
            "name_optional" to "Nom (facultatif)",
            "age" to "Âge",
            "create_account" to "CRÉER UN COMPTE",
            "terms_privacy" to "En vous connectant à Duolingo, vous acceptez nos Conditions et notre Politique de confidentialité.",
            "recaptcha" to "Ce site est protégé par reCAPTCHA Enterprise.",
            "site_language_modal" to "Langue du site",
            "done" to "Terminé",
            "welcome_back" to "Bon retour ! Connexion en cours...",
            "account_created" to "Compte créé avec succès !",
            "enter_email" to "Veuillez entrer votre e-mail ou nom d'utilisateur",
            "password_short" to "Le mot de passe doit comporter au moins 4 caractères",
            "loading" to "CHARGEMENT...",
            "how_much_know" to "Que savez-vous en %s ?",
            "new_to_lang" to "Je débute en %s",
            "know_common_words" to "Je connais quelques mots courants",
            "basic_conversations" to "Je peux avoir des conversations de base",
            "various_topics" to "Je peux parler de divers sujets",
            "topics_in_detail" to "Je peux discuter de la plupart des sujets en détail",
            "continue_caps" to "CONTINUER"
        ),
        "de" to mapOf(
            "site_language" to "SPRACHE:",
            "choose_language" to "SPRACHE WÄHLEN",
            "what_language_do_you_speak" to "Welche Sprache sprichst du?",
            "choose_interface_lang" to "Wähle deine Sprache",
            "login_caps" to "ANMELDEN",
            "signup_caps" to "REGISTRIEREN",
            "get_started_caps" to "LOS GEHEN",
            "already_have_account_caps" to "ICH HABE BEREITS EIN KONTO",
            "duolingo_on_the_go" to "Duolingo für unterwegs",
            "hero_subtitle" to "Die kostenlose, unterhaltsame und effektive Art, eine Sprache zu lernen!",
            "why_learn" to "Warum mit Duolingo lernen?",
            "effective_fun" to "Effektiv & unterhaltsam",
            "effective_subtitle" to "Spielerische Lektionen halten dich motiviert.",
            "personalized" to "Personalisiert",
            "personalized_subtitle" to "KI, angepasst an dein Lerntempo.",
            "login_title" to "Anmelden",
            "create_profile" to "Profil erstellen",
            "email_or_username" to "E-Mail oder Benutzername",
            "password" to "Passwort",
            "forgot" to "VERGESSEN?",
            "name_optional" to "Name (optional)",
            "age" to "Alter",
            "create_account" to "KONTO ERSTELLEN",
            "terms_privacy" to "Durch die Anmeldung stimmst du den Nutzungsbedingungen und Datenschutzbestimmungen zu.",
            "recaptcha" to "Geschützt durch reCAPTCHA Enterprise.",
            "site_language_modal" to "Sprache",
            "done" to "Fertig",
            "welcome_back" to "Willkommen zurück! Anmelden...",
            "account_created" to "Konto erfolgreich erstellt!",
            "enter_email" to "Bitte E-Mail oder Benutzernamen eingeben",
            "password_short" to "Passwort muss mindestens 4 Zeichen lang sein",
            "loading" to "LADEN...",
            "how_much_know" to "Wie viel %s kannst du?",
            "new_to_lang" to "Ich bin neu in %s",
            "know_common_words" to "Ich kenne einige gebräuchliche Wörter",
            "basic_conversations" to "Ich kann einfache Gespräche führen",
            "various_topics" to "Ich kann über verschiedene Themen sprechen",
            "topics_in_detail" to "Ich kann die meisten Themen ausführlich besprechen",
            "continue_caps" to "WEITER"
        ),
        "ar" to mapOf(
            "site_language" to "لغة الموقع:",
            "choose_language" to "اختر اللغة",
            "what_language_do_you_speak" to "ما هي اللغة التي تتحدث بها؟",
            "choose_interface_lang" to "اختر لغة الموقع والواجهة",
            "login_caps" to "تسجيل الدخول",
            "signup_caps" to "إنشاء حساب",
            "get_started_caps" to "ابدأ الآن",
            "already_have_account_caps" to "لدي حساب بالفعل",
            "duolingo_on_the_go" to "دولينجو في أي مكان",
            "hero_subtitle" to "الطريقة المجانية والممتعة والفعالة لتعلم اللغات!",
            "why_learn" to "لماذا تتعلم مع دولينجو؟",
            "effective_fun" to "فعال وممتع",
            "effective_subtitle" to "دروس التلعيب تبقيك محفزاً.",
            "personalized" to "مخصص لك",
            "personalized_subtitle" to "ذكاء اصطناعي يتكيف مع سرعة تعلمك.",
            "login_title" to "تسجيل الدخول",
            "create_profile" to "إنشاء ملف شخصي",
            "email_or_username" to "البريد الإلكتروني أو اسم المستخدم",
            "password" to "كلمة المرور",
            "forgot" to "هل نسيت؟",
            "name_optional" to "الاسم (اختياري)",
            "age" to "العمر",
            "create_account" to "إنشاء حساب",
            "terms_privacy" to "بتسجيل الدخول إلى دولينجو، فإنك توافق على الشروط وسياسة الخصوصية.",
            "recaptcha" to "هذا الموقع محمي بواسطة reCAPTCHA Enterprise.",
            "site_language_modal" to "لغة الموقع",
            "done" to "تم",
            "welcome_back" to "مرحباً بعودتك! جاري تسجيل الدخول...",
            "account_created" to "تم إنشاء الحساب بنجاح!",
            "enter_email" to "الرجاء إدخال البريد الإلكتروني أو اسم المستخدم",
            "password_short" to "يجب أن تكون كلمة المرور 4 أحرف على الأقل",
            "loading" to "جاري التحميل...",
            "how_much_know" to "كم تعرف من لغة %s؟",
            "new_to_lang" to "أنا جديد في لغة %s",
            "know_common_words" to "أعرف بعض الكلمات الشائعة",
            "basic_conversations" to "يمكنني إجراء محادثات بسيطة",
            "various_topics" to "يمكنني التحدث في مواضيع مختلفة",
            "topics_in_detail" to "يمكنني مناقشة معظم المواضيع بالتفصيل",
            "continue_caps" to "متابعة"
        ),
        "bn" to mapOf(
            "site_language" to "সাইটের ভাষা:",
            "choose_language" to "ভাষা বেছে নিন",
            "what_language_do_you_speak" to "আপনি কোন ভাষায় কথা বলেন?",
            "choose_interface_lang" to "আপনার ভাষা নির্বাচন করুন",
            "login_caps" to "লগ ইন",
            "signup_caps" to "সাইন আপ",
            "get_started_caps" to "শুরু করুন",
            "already_have_account_caps" to "আমার একটি অ্যাকাউন্ট আছে",
            "duolingo_on_the_go" to "ডুওলিঙ্গো চলতে চলতে",
            "hero_subtitle" to "ভাষা শেখার বিনামূল্যে, মজাদার এবং কার্যকর উপায়!",
            "why_learn" to "কেন ডুওলিঙ্গো বেছে নেবেন?",
            "effective_fun" to "কার্যকর ও মজাদার",
            "effective_subtitle" to "গেমের মতো পাঠ আপনাকে অনুপ্রাণিত রাখে।",
            "personalized" to "ব্যক্তিগতকৃত",
            "personalized_subtitle" to "আপনার শেখার গতির সাথে মানানসই এআই।",
            "login_title" to "লগ ইন করুন",
            "create_profile" to "প্রোফাইল তৈরি করুন",
            "email_or_username" to "ইমেল বা ইউজারনেম",
            "password" to "পাসওয়ার্ড",
            "forgot" to "ভুলে গেছেন?",
            "name_optional" to "নাম (ঐচ্ছিক)",
            "age" to "বয়স",
            "create_account" to "অ্যাকাউন্ট তৈরি করুন",
            "terms_privacy" to "লগ ইন করে আপনি শর্তাবলী এবং গোপনীয়তা নীতিতে সম্মত হন।",
            "recaptcha" to "সুরক্ষিত reCAPTCHA Enterprise দ্বারা।",
            "site_language_modal" to "সাইটের ভাষা",
            "done" to "সম্পন্ন",
            "welcome_back" to "স্বাগতম! লগ ইন হচ্ছে...",
            "account_created" to "অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে!",
            "enter_email" to "ইমেল বা ইউজারনেম দিন",
            "password_short" to "পাসওয়ার্ড কমপক্ষে ৪ অক্ষরের হতে হবে",
            "loading" to "লোড হচ্ছে...",
            "how_much_know" to "আপনি কতটা %s জানেন?",
            "new_to_lang" to "আমি %s তে নতুন",
            "know_common_words" to "আমি কিছু সাধারণ শব্দ জানি",
            "basic_conversations" to "আমি প্রাথমিক কথাবার্তা বলতে পারি",
            "various_topics" to "আমি বিভিন্ন বিষয়ে কথা বলতে পারি",
            "topics_in_detail" to "আমি বিস্তারিতভাবে বেশিরভাগ বিষয়ে আলোচনা করতে পারি",
            "continue_caps" to "চালিয়ে যান"
        ),
        "pl" to mapOf(
            "site_language" to "JĘZYK STRONY:",
            "choose_language" to "WYBIERZ JĘZYK",
            "what_language_do_you_speak" to "W jakim języku mówisz?",
            "choose_interface_lang" to "Wybierz język interfejsu",
            "login_caps" to "ZALOGUJ SIĘ",
            "signup_caps" to "ZAREJESTRUJ SIĘ",
            "get_started_caps" to "ROZPOCZNIJ",
            "already_have_account_caps" to "MAM JUŻ KONTO",
            "duolingo_on_the_go" to "Duolingo w podróży",
            "hero_subtitle" to "Darmowy, skuteczny i przyjemny sposób na naukę języków!",
            "why_learn" to "Dlaczego Duolingo?",
            "effective_fun" to "Skuteczne i zabawne",
            "effective_subtitle" to "Grywalizacja utrzymuje Twoją motywację.",
            "personalized" to "Spersonalizowane",
            "personalized_subtitle" to "AI dostosowane do Twojego tempa.",
            "login_title" to "Zaloguj się",
            "create_profile" to "Utwórz profil",
            "email_or_username" to "E-mail lub nazwa użytkownika",
            "password" to "Hasło",
            "forgot" to "NIE PAMIĘTASZ?",
            "name_optional" to "Imię (opcjonalnie)",
            "age" to "Wiek",
            "create_account" to "UTWÓRZ KONTO",
            "terms_privacy" to "Logując się, zgadzasz się z Regulaminem i Polityką Prywatności.",
            "recaptcha" to "Chronione przez reCAPTCHA Enterprise.",
            "site_language_modal" to "Język strony",
            "done" to "Gotowe",
            "welcome_back" to "Witaj ponownie! Logowanie...",
            "account_created" to "Konto zostało utworzone!",
            "enter_email" to "Wprowadź e-mail lub nazwę użytkownika",
            "password_short" to "Hasło musi mieć co najmniej 4 znaki",
            "loading" to "ŁADOWANIE...",
            "how_much_know" to "Ile %s znasz?",
            "new_to_lang" to "Jestem nowy w %s",
            "know_common_words" to "Znam kilka podstawowych słów",
            "basic_conversations" to "Potrafię prowadzić proste rozmowy",
            "various_topics" to "Mogę rozmawiać na różne tematy",
            "topics_in_detail" to "Mogę szczegółowo omawiać większość tematów",
            "continue_caps" to "KONTYNUUJ"
        ),
        "ro" to mapOf(
            "site_language" to "LIMBA SITE-ULUI:",
            "choose_language" to "ALEGE LIMBA",
            "what_language_do_you_speak" to "Ce limbă vorbești?",
            "choose_interface_lang" to "Alege limba interfeței",
            "login_caps" to "AUTENTIFICARE",
            "signup_caps" to "INREGISTRARE",
            "get_started_caps" to "ÎNCEPE",
            "already_have_account_caps" to "AM DEJA UN CONT",
            "duolingo_on_the_go" to "Duolingo în mișcare",
            "hero_subtitle" to "Calea gratuită, distractivă și eficientă de a învăța o limbă!",
            "why_learn" to "De ce Duolingo?",
            "effective_fun" to "Eficient și distractiv",
            "effective_subtitle" to "Lecțiile interactive te mențin motivat.",
            "personalized" to "Personalizat",
            "personalized_subtitle" to "IA adaptată la ritmul tău.",
            "login_title" to "Autentificare",
            "create_profile" to "Creează profil",
            "email_or_username" to "E-mail sau nume de utilizator",
            "password" to "Parolă",
            "forgot" to "AI UITAT?",
            "name_optional" to "Nume (opțional)",
            "age" to "Vârstă",
            "create_account" to "CREEAZĂ CONT",
            "terms_privacy" to "Prin autentificare, ești de acord cu Termenii și Politica de Confidențialitate.",
            "recaptcha" to "Protejat de reCAPTCHA Enterprise.",
            "site_language_modal" to "Limba site-ului",
            "done" to "Gata",
            "welcome_back" to "Bine ai revenit! Se autentifică...",
            "account_created" to "Cont creat cu succes!",
            "enter_email" to "Introdu e-mailul sau numele de utilizator",
            "password_short" to "Parola trebuie să aibă cel puțin 4 caractere",
            "loading" to "SE ÎNCARCĂ...",
            "how_much_know" to "Cât %s știi?",
            "new_to_lang" to "Sunt nou în %s",
            "know_common_words" to "Știu câteva cuvinte uzuale",
            "basic_conversations" to "Pot purta conversații de bază",
            "various_topics" to "Pot vorbi despre diverse subiecte",
            "topics_in_detail" to "Pot discuta în detaliu majoritatea subiectelor",
            "continue_caps" to "CONTINUĂ"
        ),
        "sv" to mapOf(
            "site_language" to "WEBBPLATSSPRÅK:",
            "choose_language" to "VÄLJ SPRÅK",
            "what_language_do_you_speak" to "Vilket språk talar du?",
            "choose_interface_lang" to "Välj gränssnittsspråk",
            "login_caps" to "LOGGA IN",
            "signup_caps" to "SKAPA KONTO",
            "get_started_caps" to "KOM IGÅNG",
            "already_have_account_caps" to "JAG HAR REDAN ETT KONTO",
            "duolingo_on_the_go" to "Duolingo på språng",
            "hero_subtitle" to "Det gratis, roliga och effektiva sättet att lära sig språk!",
            "why_learn" to "Varför lära sig med Duolingo?",
            "effective_fun" to "Effektivt & roligt",
            "effective_subtitle" to "Spelifierade lektioner håller dig motiverad.",
            "personalized" to "Personligt",
            "personalized_subtitle" to "AI anpassad efter din inlärningstakt.",
            "login_title" to "Logga in",
            "create_profile" to "Skapa profil",
            "email_or_username" to "E-post eller användarnamn",
            "password" to "Lösenord",
            "forgot" to "GLÖMT?",
            "name_optional" to "Namn (valfritt)",
            "age" to "Ålder",
            "create_account" to "SKAPA KONTO",
            "terms_privacy" to "Genom att logga in godkänner du våra villkor och integritetspolicy.",
            "recaptcha" to "Skyddas av reCAPTCHA Enterprise.",
            "site_language_modal" to "Webbplatsspråk",
            "done" to "Klar",
            "welcome_back" to "Välkommen tillbaka! Loggar in...",
            "account_created" to "Konto skapat!",
            "enter_email" to "Ange e-post eller användarnamn",
            "password_short" to "Lösenordet måste vara minst 4 tecken",
            "loading" to "LADDAR...",
            "how_much_know" to "Hur mycket %s kan du?",
            "new_to_lang" to "Jag är ny på %s",
            "know_common_words" to "Jag kan några vanliga ord",
            "basic_conversations" to "Jag kan föra enkla samtal",
            "various_topics" to "Jag kan tala om olika ämnen",
            "topics_in_detail" to "Jag kan diskutera de flesta ämnen i detalj",
            "continue_caps" to "FORTSÄTT"
        ),
        "ta" to mapOf(
            "site_language" to "தளத்தின் மொழி:",
            "choose_language" to "மொழியைத் தேர்ந்தெடு",
            "what_language_do_you_speak" to "நீங்கள் என்ன மொழி பேசுகிறீர்கள்?",
            "choose_interface_lang" to "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
            "login_caps" to "உள்நுழை",
            "signup_caps" to "பதிவுசெய்",
            "get_started_caps" to "தொடங்குங்கள்",
            "already_have_account_caps" to "என்னிடம் கணக்கு உள்ளது",
            "duolingo_on_the_go" to "பயணத்தின்போது டியூஓலிங்கோ",
            "hero_subtitle" to "இலவசமாக, சுவாரஸ்யமாக மொழி கற்க சிறந்த வழி!",
            "why_learn" to "ஏன் டியூஓலிங்கோ?",
            "effective_fun" to "பயனுள்ள மற்றும் சுவாரஸ்யமானது",
            "effective_subtitle" to "விளையாட்டு போன்ற பாடங்கள் ஊக்கமளிக்கும்.",
            "personalized" to "தனிப்பயனாக்கப்பட்டது",
            "personalized_subtitle" to "உங்கள் வேகத்திற்கு ஏற்ற AI.",
            "login_title" to "உள்நுழைக",
            "create_profile" to "சுயவிவரத்தை உருவாக்கு",
            "email_or_username" to "மின்னஞ்சல் அல்லது பயனர் பெயர்",
            "password" to "கடவுச்சொல்",
            "forgot" to "மறந்துவிட்டதா?",
            "name_optional" to "பெயர் (விருப்பமானது)",
            "age" to "வயது",
            "create_account" to "கணக்கை உருவாக்கு",
            "terms_privacy" to "உள்நுழைவதன் மூலம் எங்கள் விதிகளை ஏற்கிறீர்கள்.",
            "recaptcha" to "reCAPTCHA Enterprise மூலம் பாதுகாக்கப்பட்டது.",
            "site_language_modal" to "தளத்தின் மொழி",
            "done" to "முடிந்தது",
            "welcome_back" to "மீண்டும் வருக! உள்நுழைகிறது...",
            "account_created" to "கணக்கு உருவாக்கப்பட்டது!",
            "enter_email" to "மின்னஞ்சலை உள்ளிடவும்",
            "password_short" to "கடவுச்சொல் 4 எழுத்துக்கள் இருக்க வேண்டும்",
            "loading" to "ஏற்றுகிறது...",
            "how_much_know" to "உங்களுக்கு কতটা %s தெரியும்?",
            "new_to_lang" to "நான் %s க்கு புதியவன்",
            "know_common_words" to "எனக்கு சில பொதுவான சொற்கள் தெரியும்",
            "basic_conversations" to "என்னால் அடிப்படை உரையாடல்களை செய்ய முடியும்",
            "various_topics" to "என்னால் பல தலைப்புகளைப் பற்றி பேச முடியும்",
            "topics_in_detail" to "பெரும்பாலான தலைப்புகளை விரிவாக விவாதிக்க முடியும்",
            "continue_caps" to "தொடரவும்"
        ),
        "te" to mapOf(
            "site_language" to "సైట్ భాష:",
            "choose_language" to "భాషను ఎంచుకోండి",
            "what_language_do_you_speak" to "మీరు ఏ భాష మాట్లాడతారు?",
            "choose_interface_lang" to "మీ భాషను ఎంచుకోండి",
            "login_caps" to "లాగిన్",
            "signup_caps" to "సైన్ అప్",
            "get_started_caps" to "ప్రారంభించండి",
            "already_have_account_caps" to "నాకు ఇప్పటికే ఖాతా ఉంది",
            "duolingo_on_the_go" to "ఎల్లవేళలా డ్యూఓలింగో",
            "hero_subtitle" to "భాష నేర్చుకోవడానికి ఉచిత మరియు ప్రభావవంతమైన మార్గం!",
            "why_learn" to "డ్యూఓలింగో ఎందుకు?",
            "effective_fun" to "సమర్థవంతమైన & సరదా",
            "effective_subtitle" to "ఆటల వంటి పాఠాలు మిమ్మల్ని ప్రోత్సహిస్తాయి.",
            "personalized" to "వ్యక్తిగతీకరించబడింది",
            "personalized_subtitle" to "మీ వేగానికి అనుగుణంగా AI.",
            "login_title" to "లాగిన్ చేయండి",
            "create_profile" to "ప్రొఫైల్ సృష్టించండి",
            "email_or_username" to "ఈమెయిల్ లేదా యూజర్‌నేమ్",
            "password" to "పాస్‌వర్డ్",
            "forgot" to "మరిచిపోయారా?",
            "name_optional" to "పేరు (ఐచ్ఛికం)",
            "age" to "వయస్సు",
            "create_account" to "ఖాతాను సృష్టించండి",
            "terms_privacy" to "లాగిన్ చేయడం ద్వారా నిబంధనలను అంగీకరిస్తున్నారు.",
            "recaptcha" to "reCAPTCHA ఎంటర్‌ప్రైజ్ రక్షణలో ఉంది.",
            "site_language_modal" to "సైట్ భాష",
            "done" to "పూర్తయింది",
            "welcome_back" to "స్వాగతం! లాగిన్ అవుతోంది...",
            "account_created" to "ఖాతా సృష్టించబడింది!",
            "enter_email" to "ఈమెయిల్ లేదా యూజర్‌నేమ్ నమోదు చేయండి",
            "password_short" to "పాస్‌వర్డ్ కనీసం 4 అక్షరాలు ఉండాలి",
            "loading" to "లోడ్ అవుతోంది...",
            "how_much_know" to "మీకు %s ఎంత తెలుసు?",
            "new_to_lang" to "నేను %s కి కొత్త",
            "know_common_words" to "నాకు కొన్ని సాధారణ పదాలు తెలుసు",
            "basic_conversations" to "నేను ప్రాథమిక సంభాషణలు చేయగలను",
            "various_topics" to "నేను వివిధ అంశాల గురించి మాట్లాడగలను",
            "topics_in_detail" to "నేను చాలా అంశాలను వివరంగా చర్చించగలను",
            "continue_caps" to "కొనసాగించు"
        ),
        "th" to mapOf(
            "site_language" to "ภาษาของเว็บไซต์:",
            "choose_language" to "เลือกภาษา",
            "what_language_do_you_speak" to "คุณพูดภาษาอะไร?",
            "choose_interface_lang" to "เลือกภาษาของอินเทอร์เฟซ",
            "login_caps" to "เข้าสู่ระบบ",
            "signup_caps" to "ลงทะเบียน",
            "get_started_caps" to "เริ่มต้นใช้งาน",
            "already_have_account_caps" to "ฉันมีบัญชีอยู่แล้ว",
            "duolingo_on_the_go" to "Duolingo พกพาไปได้ทุกที่",
            "hero_subtitle" to "วิธีเรียนภาษาฟรี สนุก และได้ผลจริง!",
            "why_learn" to "ทำไมต้องเรียนกับ Duolingo?",
            "effective_fun" to "ได้ผลและสนุกสนาน",
            "effective_subtitle" to "บทเรียนสไตล์เกมช่วยสร้างแรงจูงใจ",
            "personalized" to "ส่วนบุคคล",
            "personalized_subtitle" to "AI ปรับให้เข้ากับความเร็วของคุณ",
            "login_title" to "เข้าสู่ระบบ",
            "create_profile" to "สร้างโปรไฟล์",
            "email_or_username" to "อีเมลหรือชื่อผู้ใช้",
            "password" to "รหัสผ่าน",
            "forgot" to "ลืมรหัสผ่าน?",
            "name_optional" to "ชื่อ (ไม่บังคับ)",
            "age" to "อายุ",
            "create_account" to "สร้างบัญชี",
            "terms_privacy" to "การเข้าสู่ระบบแสดงว่าคุณยอมรับข้อตกลง",
            "recaptcha" to "ได้รับการคุ้มครองโดย reCAPTCHA Enterprise",
            "site_language_modal" to "ภาษาของเว็บไซต์",
            "done" to "เสร็จสิ้น",
            "welcome_back" to "ยินดีต้อนรับกลับ! กำลังเข้าสู่ระบบ...",
            "account_created" to "สร้างบัญชีสำเร็จ!",
            "enter_email" to "กรุณากรอกอีเมลหรือชื่อผู้ใช้",
            "password_short" to "รหัสผ่านต้องมีอย่างน้อย 4 ตัวอักษร",
            "loading" to "กำลังโหลด...",
            "how_much_know" to "คุณรู้ภาษา %s แค่ไหน?",
            "new_to_lang" to "ฉันเพิ่งเริ่มเรียน %s",
            "know_common_words" to "ฉันรู้คำศัพท์ทั่วไปบางคำ",
            "basic_conversations" to "ฉันสนทนาพื้นฐานได้",
            "various_topics" to "ฉันพูดคุยได้หลากหลายหัวข้อ",
            "topics_in_detail" to "ฉันพูดคุยรายละเอียดหัวข้อส่วนใหญ่ได้",
            "continue_caps" to "ดำเนินการต่อ"
        ),
        "tl" to mapOf(
            "site_language" to "WIKA NG SITE:",
            "choose_language" to "PUMILI NG WIKA",
            "what_language_do_you_speak" to "Anong wika ang sinasalita mo?",
            "choose_interface_lang" to "Pumili ng wika ng site",
            "login_caps" to "MAG-LOG IN",
            "signup_caps" to "MAG-SIGN UP",
            "get_started_caps" to "MAGSIMULA",
            "already_have_account_caps" to "MAY ACCOUNT NA AKO",
            "duolingo_on_the_go" to "Duolingo kahit saan",
            "hero_subtitle" to "Libre, masaya, at epektibong paraan para matuto ng wika!",
            "why_learn" to "Bakit matuto sa Duolingo?",
            "effective_fun" to "Epektibo at Masaya",
            "effective_subtitle" to "Laro-tulad na mga aralin para sa motibasyon.",
            "personalized" to "Personalized",
            "personalized_subtitle" to "AI na inangkop sa bilis mo.",
            "login_title" to "Mag-log in",
            "create_profile" to "Gumawa ng profile",
            "email_or_username" to "Email o username",
            "password" to "Password",
            "forgot" to "NAKALIMUTAN?",
            "name_optional" to "Pangalan (opsyonal)",
            "age" to "Edad",
            "create_account" to "GUMAWA NG ACCOUNT",
            "terms_privacy" to "Sa pag-log in, sumasang-ayon ka sa aming Mga Tuntunin.",
            "recaptcha" to "Protektado ng reCAPTCHA Enterprise.",
            "site_language_modal" to "Wika ng Site",
            "done" to "Tapos na",
            "welcome_back" to "Maligayang pagbabalik! Nag-lo-log in...",
            "account_created" to "Matagumpay na nagawa ang account!",
            "enter_email" to "Mangyaring ilagay ang email o username",
            "password_short" to "Ang password ay dapat hindi bababa sa 4 na character",
            "loading" to "NAG-A-UPLOAD...",
            "how_much_know" to "Gaano karami ang alam mo sa %s?",
            "new_to_lang" to "Bago ako sa %s",
            "know_common_words" to "May alam akong ilang karaniwang salita",
            "basic_conversations" to "Kaya kong magkaroon ng simpleng usapan",
            "various_topics" to "Kaya kong magsalita tungkol sa iba't ibang paksa",
            "topics_in_detail" to "Kaya kong talakayin ang karamihan sa mga paksa nang detalyado",
            "continue_caps" to "IPAGPATULOY"
        ),
        "tr" to mapOf(
            "site_language" to "SİTE DİLİ:",
            "choose_language" to "DİL SEÇİN",
            "what_language_do_you_speak" to "Hangi dili konuşuyorsunuz?",
            "choose_interface_lang" to "Site dilinizi seçin",
            "login_caps" to "GİRİŞ YAP",
            "signup_caps" to "KAYIT OL",
            "get_started_caps" to "BAŞLA",
            "already_have_account_caps" to "ZATEN HESABIM VAR",
            "duolingo_on_the_go" to "Her yerde Duolingo",
            "hero_subtitle" to "Dil öğrenmenin ücretsiz, eğlenceli ve etkili yolu!",
            "why_learn" to "Neden Duolingo?",
            "effective_fun" to "Etkili ve Eğlenceli",
            "effective_subtitle" to "Oyunlaştırılmış dersler motivasyon sağlar.",
            "personalized" to "Kişiselleştirilmiş",
            "personalized_subtitle" to "Hızınıza göre uyarlanan yapay zeka.",
            "login_title" to "Giriş yap",
            "create_profile" to "Profil oluştur",
            "email_or_username" to "E-posta veya kullanıcı adı",
            "password" to "Şifre",
            "forgot" to "UNUTTUN MU?",
            "name_optional" to "İsim (isteğe bağlı)",
            "age" to "Yaş",
            "create_account" to "HESAP OLUŞTUR",
            "terms_privacy" to "Giriş yaparak Koşullarımızı ve Gizlilik Politikamızı kabul etmiş olursunuz.",
            "recaptcha" to "reCAPTCHA Enterprise ile korunmaktadır.",
            "site_language_modal" to "Site Dili",
            "done" to "Tamam",
            "welcome_back" to "Tekrar hoş geldiniz! Giriş yapılıyor...",
            "account_created" to "Hesap başarıyla oluşturuldu!",
            "enter_email" to "Lütfen e-posta veya kullanıcı adınızı girin",
            "password_short" to "Şifre en az 4 karakter olmalıdır",
            "loading" to "YÜKLENİYOR...",
            "how_much_know" to "Ne kadar %s biliyorsun?",
            "new_to_lang" to "%s konusunda yeniyim",
            "know_common_words" to "Bazı yaygın kelimeleri biliyorum",
            "basic_conversations" to "Basit konuşmalar yapabilirim",
            "various_topics" to "Çeşitli konular hakkında konuşabilirim",
            "topics_in_detail" to "Çoğu konuyu detaylıca tartışabilirim",
            "continue_caps" to "DEVAM ET"
        ),
        "uk" to mapOf(
            "site_language" to "МОВА САЙТУ:",
            "choose_language" to "ОБРАТИ МОВУ",
            "what_language_do_you_speak" to "Якою мовою ви розмовляєте?",
            "choose_interface_lang" to "Оберіть мову інтерфейсу",
            "login_caps" to "УВІЙТИ",
            "signup_caps" to "РЕЄСТРАЦІЯ",
            "get_started_caps" to "РОЗПОЧАТИ",
            "already_have_account_caps" to "Я ВЖЕ МАЮ ОБЛІКОВИЙ ЗАПИС",
            "duolingo_on_the_go" to "Duolingo завжди поруч",
            "hero_subtitle" to "Безкоштовний, веселий та ефективний спосіб вивчати мови!",
            "why_learn" to "Чому саме Duolingo?",
            "effective_fun" to "Ефективно та весело",
            "effective_subtitle" to "Ігрові уроки підтримують мотивацію.",
            "personalized" to "Персоналізовано",
            "personalized_subtitle" to "ШІ адаптується до вашого темпу.",
            "login_title" to "Увійти",
            "create_profile" to "Створити профіль",
            "email_or_username" to "Ел. пошта або ім'я користувача",
            "password" to "Пароль",
            "forgot" to "ЗАБУЛИ?",
            "name_optional" to "Ім'я (необов'язково)",
            "age" to "Вік",
            "create_account" to "СТВОРИТИ АКАУНТ",
            "terms_privacy" to "Входячи, ви погоджуєтеся з Умовами та Політикою конфіденційності.",
            "recaptcha" to "Захищено за допомогою reCAPTCHA Enterprise.",
            "site_language_modal" to "Мова сайту",
            "done" to "Готово",
            "welcome_back" to "З поверненням! Вхід...",
            "account_created" to "Обліковий запис успішно створено!",
            "enter_email" to "Введіть пошту або ім'я користувача",
            "password_short" to "Пароль має бути не менше 4 символів",
            "loading" to "ЗАВАНТАЖЕННЯ...",
            "how_much_know" to "Скільки %s ви знаєте?",
            "new_to_lang" to "Я новачок у %s",
            "know_common_words" to "Я знаю кілька простих слів",
            "basic_conversations" to "Можу вести прості розмови",
            "various_topics" to "Можу говорити на різні теми",
            "topics_in_detail" to "Можу детально обговорювати більшість тем",
            "continue_caps" to "ПРОДОВЖИТИ"
        ),
        "ur" to mapOf(
            "site_language" to "سائٹ کی زبان:",
            "choose_language" to "زبان منتخب کریں",
            "what_language_do_you_speak" to "آپ کون سی زبان بولتے ہیں؟",
            "choose_interface_lang" to "اپنی زبان منتخب کریں",
            "login_caps" to "لاگ ان",
            "signup_caps" to "سائن اپ",
            "get_started_caps" to "شروع کریں",
            "already_have_account_caps" to "میرا پہلے سے اکاؤنٹ ہے",
            "duolingo_on_the_go" to "ہر جگہ ڈوئولنگو",
            "hero_subtitle" to "زبان سیکھنے کا مفت، پر لطف اور مؤثر طریقہ!",
            "why_learn" to "ڈوئولنگو کے ساتھ کیوں سیکھیں؟",
            "effective_fun" to "مؤثر اور پرلطف",
            "effective_subtitle" to "کھیل جیسے اسباق آپ کو متحرک رکھتے ہیں۔",
            "personalized" to "ذاتی نوعیت کا",
            "personalized_subtitle" to "آپ کی رفتار کے مطابق AI۔",
            "login_title" to "لاگ ان کریں",
            "create_profile" to "پروفائل بنائیں",
            "email_or_username" to "ای میل یا یوزر نیم",
            "password" to "پاس ورڈ",
            "forgot" to "بھول گئے؟",
            "name_optional" to "نام (اختیاری)",
            "age" to "عمر",
            "create_account" to "اکاؤنٹ بنائیں",
            "terms_privacy" to "لاگ ان کرکے، آپ ہماری شرائط سے اتفاق کرتے ہیں۔",
            "recaptcha" to "reCAPTCHA انٹرپرائز کے ذریعے محفوظ ہے۔",
            "site_language_modal" to "سائٹ کی زبان",
            "done" to "مکمل",
            "welcome_back" to "خوش آمدید! لاگ ان ہو رہا ہے...",
            "account_created" to "اکاؤنٹ کامیابی سے بن گیا!",
            "enter_email" to "براہ کرم اپنا ای میل یا یوزر نیم درج کریں",
            "password_short" to "پاس ورڈ کم از کم 4 حروف کا ہونا چاہیے",
            "loading" to "لوڈنگ ہو رہی ہے...",
            "how_much_know" to "آپ کتنی %s جانتے ہیں؟",
            "new_to_lang" to "میں %s میں نیا ہوں",
            "know_common_words" to "مجھے کچھ عام الفاظ معلوم ہیں",
            "basic_conversations" to "میں بنیادی بات چیت کر سکتا ہوں",
            "various_topics" to "میں مختلف موضوعات پر بات کر سکتا ہوں",
            "topics_in_detail" to "میں تفصیل کے ساتھ زیادہ تر موضوعات پر بحث کر سکتا ہوں",
            "continue_caps" to "جاری رکھیں"
        ),
        "ja" to mapOf(
            "site_language" to "サイト言語:",
            "choose_language" to "言語を選択",
            "what_language_do_you_speak" to "どの言語を話しますか？",
            "choose_interface_lang" to "サイトとインターフェース言語を選択",
            "login_caps" to "ログイン",
            "signup_caps" to "新規登録",
            "get_started_caps" to "始める",
            "already_have_account_caps" to "アカウントをお持ちの方",
            "duolingo_on_the_go" to "いつでもどこでもDuolingo",
            "hero_subtitle" to "無料・楽しく・効果的に新しい言語を学ぼう！",
            "why_learn" to "Duolingoで学ぶ理由",
            "effective_fun" to "効果的で楽しい",
            "effective_subtitle" to "ゲーム感覚でレッスンを継続。",
            "personalized" to "パーソナライズ",
            "personalized_subtitle" to "あなたの学習ペースに合わせたAI。",
            "login_title" to "ログイン",
            "create_profile" to "プロフィール作成",
            "email_or_username" to "メールアドレスまたはユーザー名",
            "password" to "パスワード",
            "forgot" to "パスワードをお忘れですか？",
            "name_optional" to "名前（任意）",
            "age" to "年齢",
            "create_account" to "アカウントを作成",
            "terms_privacy" to "ログインすると利用規約とプライバシーポリシーに同意したことになります。",
            "recaptcha" to "reCAPTCHA Enterpriseで保護されています。",
            "site_language_modal" to "サイト言語",
            "done" to "完了",
            "welcome_back" to "おかえりなさい！ログイン中...",
            "account_created" to "アカウントを作成しました！",
            "enter_email" to "メールアドレスまたはユーザー名を入力してください",
            "password_short" to "パスワードは4文字以上で入力してください",
            "loading" to "読み込み中...",
            "how_much_know" to "%s をどのくらい知っていますか？",
            "new_to_lang" to "%s は初めてです",
            "know_common_words" to "日常的な単語をいくつか知っています",
            "basic_conversations" to "簡単な会話ができます",
            "various_topics" to "さまざまなトピックについて話せます",
            "topics_in_detail" to "ほとんどのトピックを詳しく議論できます",
            "continue_caps" to "次へ"
        ),
        "ko" to mapOf(
            "site_language" to "사이트 언어:",
            "choose_language" to "언어 선택",
            "what_language_do_you_speak" to "어떤 언어를 사용하시나요?",
            "choose_interface_lang" to "사이트 언어를 선택하세요",
            "login_caps" to "로그인",
            "signup_caps" to "가입하기",
            "get_started_caps" to "시작하기",
            "already_have_account_caps" to "이미 계정이 있습니다",
            "duolingo_on_the_go" to "언제 어디서나 듀오링고",
            "hero_subtitle" to "무료로 재미있고 효과적으로 언어를 배워보세요!",
            "why_learn" to "왜 듀오링고로 배워야 할까요?",
            "effective_fun" to "효과적이고 재미있는 학습",
            "effective_subtitle" to "게임 같은 레슨으로 꾸준히 학습하세요.",
            "personalized" to "개인 맞춤형",
            "personalized_subtitle" to "학습 속도에 맞춘 AI 기술.",
            "login_title" to "로그인",
            "create_profile" to "프로필 만들기",
            "email_or_username" to "이메일 또는 사용자 이름",
            "password" to "비밀번호",
            "forgot" to "비밀번호를 잊으셨나요?",
            "name_optional" to "이름 (선택 사항)",
            "age" to "나이",
            "create_account" to "계정 만들기",
            "terms_privacy" to "로그인하면 듀오링고의 이용 약관 및 개인정보 처리방침에 동의하게 됩니다.",
            "recaptcha" to "이 사이트는 reCAPTCHA Enterprise로 보호됩니다.",
            "site_language_modal" to "사이트 언어",
            "done" to "완료",
            "welcome_back" to "다시 오신 것을 환영합니다! 로그인 중...",
            "account_created" to "계정이 성공적으로 생성되었습니다!",
            "enter_email" to "이메일 또는 사용자 이름을 입력하세요",
            "password_short" to "비밀번호는 최소 4자 이상이어야 합니다",
            "loading" to "로딩 중...",
            "how_much_know" to "%s 에 대해 얼마나 알고 계신가요?",
            "new_to_lang" to "%s 은(는) 처음입니다",
            "know_common_words" to "기본적인 단어를 몇 개 알고 있습니다",
            "basic_conversations" to "기초적인 대화를 할 수 있습니다",
            "various_topics" to "다양한 주제에 대해 이야기할 수 있습니다",
            "topics_in_detail" to "대부분의 주제를 자세히 토론할 수 있습니다",
            "continue_caps" to "계속"
        ),
        "zh" to mapOf(
            "site_language" to "网站语言:",
            "choose_language" to "选择语言",
            "what_language_do_you_speak" to "您使用什么语言？",
            "choose_interface_lang" to "选择您的界面语言",
            "login_caps" to "登录",
            "signup_caps" to "注册",
            "get_started_caps" to "开始",
            "already_have_account_caps" to "已有账户",
            "duolingo_on_the_go" to "随时随地学 Duolingo",
            "hero_subtitle" to "免费、有趣且高效的语言学习方式！",
            "why_learn" to "为什么选择 Duolingo？",
            "effective_fun" to "高效且有趣",
            "effective_subtitle" to "游戏化课程让你保持学习动力。",
            "personalized" to "个性化推荐",
            "personalized_subtitle" to "量身定制的 AI 学习节奏。",
            "login_title" to "登录",
            "create_profile" to "创建个人资料",
            "email_or_username" to "电子邮箱或用户名",
            "password" to "密码",
            "forgot" to "忘记密码？",
            "name_optional" to "姓名（可选）",
            "age" to "年龄",
            "create_account" to "创建账户",
            "terms_privacy" to "登录 Duolingo 即表示您同意我们的服务条款和隐私政策。",
            "recaptcha" to "本网站受 reCAPTCHA Enterprise 保护。",
            "site_language_modal" to "网站语言",
            "done" to "完成",
            "welcome_back" to "欢迎回来！正在登录...",
            "account_created" to "账户创建成功！",
            "enter_email" to "请输入您的电子邮箱或用户名",
            "password_short" to "密码长度必须至少为 4 个字符",
            "loading" to "加载中...",
            "how_much_know" to "您对 %s 了解多少？",
            "new_to_lang" to "我刚开始学习 %s",
            "know_common_words" to "我了解一些常用单词",
            "basic_conversations" to "我可以进行简单的日常对话",
            "various_topics" to "我可以讨论各种主题",
            "topics_in_detail" to "我可以深入讨论大多数话题",
            "continue_caps" to "继续"
        ),
        "it" to mapOf(
            "site_language" to "LINGUA DEL SITO:",
            "choose_language" to "SCEGLI LINGUA",
            "what_language_do_you_speak" to "Che lingua parli?",
            "choose_interface_lang" to "Scegli la lingua del sito e dell'interfaccia",
            "login_caps" to "ACCEDI",
            "signup_caps" to "REGISTRATI",
            "get_started_caps" to "INIZIA",
            "already_have_account_caps" to "HO GIÀ UN ACCOUNT",
            "duolingo_on_the_go" to "Duolingo in movimento",
            "hero_subtitle" to "Il modo gratuito, divertente ed efficace per imparare una lingua!",
            "why_learn" to "Perché imparare con Duolingo?",
            "effective_fun" to "Efficace e divertente",
            "effective_subtitle" to "Lezioni divertenti per tenerti motivato.",
            "personalized" to "Personalizzato",
            "personalized_subtitle" to "IA adattata al tuo ritmo di apprendimento.",
            "login_title" to "Accedi",
            "create_profile" to "Crea profilo",
            "email_or_username" to "E-mail o nome utente",
            "password" to "Password",
            "forgot" to "DIMENTICATA?",
            "name_optional" to "Nome (opzionale)",
            "age" to "Età",
            "create_account" to "CREA ACCOUNT",
            "terms_privacy" to "Accedendo a Duolingo, accetti i nostri Termini e l'Informativa sulla privacy.",
            "recaptcha" to "Questo sito è protetto da reCAPTCHA Enterprise.",
            "site_language_modal" to "Lingua del sito",
            "done" to "Fatto",
            "welcome_back" to "Bentornato! Accesso in corso...",
            "account_created" to "Account creato con successo!",
            "enter_email" to "Inserisci la tua e-mail o il nome utente",
            "password_short" to "La password deve contenere almeno 4 caratteri",
            "loading" to "CARICAMENTO...",
            "how_much_know" to "Quanto %s conosci?",
            "new_to_lang" to "Sono nuovo in %s",
            "know_common_words" to "Conosco alcune parole comuni",
            "basic_conversations" to "Posso fare conversazioni semplici",
            "various_topics" to "Posso parlare di vari argomenti",
            "topics_in_detail" to "Posso discutere in dettaglio la maggior parte degli argomenti",
            "continue_caps" to "CONTINUA"
        ),
        "kn" to mapOf(
            "site_language" to "ಸೈಟ್ ಭಾಷೆ:",
            "choose_language" to "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "what_language_do_you_speak" to "ನೀವು ಯಾವ ಭಾಷೆಯನ್ನು ಮಾತನಾಡುತ್ತೀರಿ?",
            "choose_interface_lang" to "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "login_caps" to "ಲಾಗಿನ್",
            "signup_caps" to "ಸೈನ್ ಅಪ್",
            "get_started_caps" to "ಪ್ರಾರಂಭಿಸಿ",
            "already_have_account_caps" to "ನನ್ನ ಬಳಿ ಈಗಾಗಲೇ ಖಾತೆ ಇದೆ",
            "duolingo_on_the_go" to "ಡುಯೋಲಿಂಗೋ",
            "hero_subtitle" to "ಉಚಿತ, ಮೋಜಿನ ಭಾಷಾ ಕಲಿಕೆ!",
            "why_learn" to "ಡುಯೋಲಿಂಗೋ ಜೊತೆ ಏಕೆ ಕಲಿಯಬೇಕು?",
            "effective_fun" to "ಪರಿಣಾಮಕಾರಿ ಮತ್ತು ಮೋಜಿನ",
            "effective_subtitle" to "ಪಾಠಗಳು ನಿಮ್ಮನ್ನು ಪ್ರೇರೇಪಿಸುತ್ತವೆ.",
            "personalized" to "ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ",
            "personalized_subtitle" to "ಕಲಿಕೆಯ ವೇಗಕ್ಕೆ ತಕ್ಕಂತೆ AI.",
            "login_title" to "ಲಾಗಿನ್ ಮಾಡಿ",
            "create_profile" to "ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
            "email_or_username" to "ಇಮೇಲ್ ಅಥವಾ ಬಳಕೆದಾರ ಹೆಸರು",
            "password" to "ಪಾಸ್‌ವರ್ಡ್",
            "forgot" to "ಮರೆತಿದ್ದೀರಾ?",
            "name_optional" to "ಹೆಸರು (ಐಚ್ಛಿಕ)",
            "age" to "ವಯಸ್ಸು",
            "create_account" to "ಖಾತೆ ರಚಿಸಿ",
            "terms_privacy" to "ಸೈನ್ ಇನ್ ಮಾಡುವ ಮೂಲಕ, ನೀವು ನಿಯಮಗಳನ್ನು ಒಪ್ಪುತ್ತೀರಿ.",
            "recaptcha" to "reCAPTCHA ದಿಂದ ಸಂರಕ್ಷಿಸಲಾಗಿದೆ.",
            "site_language_modal" to "ಸೈಟ್ ಭಾಷೆ",
            "done" to "ಪೂರ್ಣಗೊಂಡಿದೆ",
            "welcome_back" to "ಮತ್ತೆ ಸ್ವಾಗತ!",
            "account_created" to "ಖಾತೆ ರಚಿಸಲಾಗಿದೆ!",
            "enter_email" to "ಇಮೇಲ್ ನಮೂದಿಸಿ",
            "password_short" to "ಪಾಸ್‌ವರ್ಡ್ 4 ಅಕ್ಷರಗಳಿಗಿಂತ ಹೆಚ್ಚಿರಬೇಕು",
            "loading" to "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
            "how_much_know" to "ನೀವು ಎಷ್ಟು %s ಬಲ್ಲರಿ?",
            "new_to_lang" to "ನಾನು %s ಗೆ ಹೊಸಬ",
            "know_common_words" to "ಸಾಮಾನ್ಯ ಪದಗಳು ಗೊತ್ತು",
            "basic_conversations" to "ಸಾಮಾನ್ಯ ಸಂಭಾಷಣೆ ಮಾಡಬಲ್ಲೆ",
            "various_topics" to "ವಿವಿಧ ವಿಷಯಗಳ ಬಗ್ಗೆ ಮಾತನಾಡಬಲ್ಲೆ",
            "topics_in_detail" to "ವಿವರವಾಗಿ ಚರ್ಚಿಸಬಲ್ಲೆ",
            "continue_caps" to "ಮುಂದುವರಿಸಿ",
            "section_1_unit_1" to "ವಿಭಾಗ 1, ಯುನಿಟ್ 1",
            "form_basic_sentences" to "ಮೂಲ ವಾಕ್ಯಗಳನ್ನು ರಚಿಸಿ",
            "guidebook" to "ಮಾರ್ಗದರ್ಶಿ",
            "start" to "ಪ್ರಾರಂಭಿಸಿ",
            "learn" to "ಕಲಿಯಿರಿ",
            "letters" to "ಅಕ್ಷರಗಳು",
            "leaderboards" to "ಲೀಡರ್‌ಬೋರ್ಡ್‌ಗಳು",
            "quests" to "ಕ್ವೆಸ್ಟ್‌ಗಳು",
            "shop" to "ಶಾಪ್",
            "profile" to "ಪ್ರೊಫೈಲ್",
            "more" to "ಇನ್ನಷ್ಟು",
            "unlock_leaderboards" to "ಲೀಡರ್‌ಬೋರ್ಡ್‌ಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಿ!",
            "unlock_leaderboards_sub" to "ಸ್ಪರ್ಧಿಸಲು 3 ಪಾಠಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ",
            "daily_quests" to "ದೈನಂದಿನ ಕ್ವೆಸ್ಟ್‌ಗಳು",
            "view_all" to "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
            "earn_10_xp" to "10 XP ಗಳಿಸಿ",
            "create_profile_title" to "ಪ್ರೊಫೈಲ್ ರಚಿಸಿ!",
            "talk_about_food" to "ಆಹಾರದ ಬಗ್ಗೆ ಮಾತನಾಡಿ",
            "lets_go" to "ಹೋಗೋಣ!",
            "how_old_are_you" to "ನಿಮ್ಮ ವಯಸ್ಸು ಎಷ್ಟು?",
            "providing_age_info" to "ವಯಸ್ಸಿನ ಮಾಹಿತಿ.",
            "next_caps" to "ಮುಂದೆ",
            "create_your_profile" to "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
            "lets_learn_lang" to "%s ಕಲಿಯೋಣ!",
            "get_to_know_characters" to "%s ಅಕ್ಷರಗಳು ಮತ್ತು ಶಬ್ದಗಳನ್ನು ತಿಳಿಯಿರಿ",
            "learn_the_letters" to "ಅಕ್ಷರಗಳನ್ನು ಕಲಿಯಿರಿ",
            "borrowed_characters" to "ಇತರ ಅಕ್ಷರಗಳು",
            "vowels" to "ಸ್ವರಗಳು",
            "combinations" to "ಸಂಯೋಜನೆಗಳು",
            "practice_sound" to "ಉಚ್ಚಾರಣೆ ಅಭ್ಯಾಸ ಮಾಡಿ",
            "tap_to_listen" to "ಉಚ್ಚಾರಣೆ ಕೇಳಲು ಟ್ಯಾಪ್ ಮಾಡಿ"
        )
    )

    fun t(key: String, vararg args: Any): String {
        val langMap = translations[currentLanguageCode] ?: translations["en"] ?: emptyMap()
        val template = langMap[key] ?: key
        return if (args.isNotEmpty()) {
            try {
                String.format(template, *args)
            } catch (e: Exception) {
                template
            }
        } else {
            template
        }
    }

    fun string(key: String, vararg args: Any): String = t(key, *args)
}
